blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
        path('', views.ArticleListView.as_view(), name='article_list'),
        path('<int:pk>/<slug:slug>/', views.ArticleDetailView.as_view(), name='article_detail'),
        path('', views.post_update, name='update'),
        path('', views.post_delete, name='delete'),
        path('', views.post_delete, name='detail'),

]

iknow/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('blog/', include('blog.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('summernote/', include('django_summernote.urls')),

]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from tinymce.models import HTMLField






# Create your models here.
from django.urls import reverse


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published'),
        ('sketch', 'Sketch'),
    )
    title = models.CharField(max_length=120)
    content = models.TextField()
    author = models.CharField(default='Courage', max_length=150)
    created = models.DateTimeField(auto_now=False,
                                     auto_now_add=True,
                                   null=True)

    update = models.DateTimeField(auto_now=True,
                                  auto_now_add=False)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    slug = models.SlugField(max_length=1100, unique_for_date='created')

    comments = models.BooleanField(default=True)
##install Pillow from pip install Pillow to use image
    post_image = models.ImageField(upload_to='blog-image',blank=True)


    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse(
    #         'blog:article-list',
    #
    #     )

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.views.generic import (
            CreateView,
            DeleteView,
            ListView,
            DetailView
)
# Create your views here.


def post_create(request):
    template = ('blog/home.html')
    return render(request, template)

class ArticleDetailView(DetailView):
    queryset = Post.objects.filter(status='published')
    template_name = ('blog/post_detail.html')


class ArticleListView(ListView):
    model = Post
    queryset = Post.objects.filter(status='published')
    template_name = ('blog/post_list.html')
    paginate_by = 10





def post_update(request):
    template = ('blog/home.html')
    return render(request, template)

def post_delete(request):
    template = ('blog/home.html')
    return render(request, template)

blog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}{% if object.title %} {{ object.title }} : {% endif %}fullLove {% endblock %}
    </title>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" >
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'blog/css/blog_boot.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/style_boot.css' %}">
    <link rel="icon" type="image/icon" href="{% static '/img/favicon.ico' %}">
</head>

<body>
    {% block nav %} {% include 'blog/nav_boot.html' %}{% endblock %}
    {% block body %}


    {% block sidebar %}{% endblock %}

     <footer class="blog-footer">
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>
    {% endblock %}






    <!--<script src="{% static 'js/nav.js' %}"></script>-->
<!--&lt;!&ndash; Bootstrap core JavaScript &ndash;&gt;-->
    <!--<script src="{% static 'blog/jquery/jquery.min.js' %}"></script>-->
    <!--<script src="{% static 'blog/bootstrap/js/bootstrap.bundle.min.js' %}"></script>-->
    <!--<script src="{% static 'blog/bootstrap/js/bootstrap.bundle.min.js.map' %}"></script>-->
    <!--<script src="{% static 'blog/bootstrap/js/bootstrap.min.js' %}"></script>-->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static 'bootstrap/assets/js/vendor/jquery.min.js' %}"><\/script>')</script>
    <script src="{% static 'blog/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'bootstrap/assets/js/ie10-viewport-bug-workaround.js' %}"></script>



</body>

</html>

blog/templates/blog/comments.html
<!-- Comments Form -->
          <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
              <form>
                <div class="form-group">
                  <textarea class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>

<!-- Single Comment -->
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>

          <!-- Comment with nested comments -->
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

              <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                  <h5 class="mt-0">Commenter Name</h5>
                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
              </div>

              <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                  <h5 class="mt-0">Commenter Name</h5>
                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
              </div>

            </div>
          </div>

blog/templates/blog/footer.html
<footer class="blog-footer">
      <p>&nbsp;&nbsp;&nbsp;&nbsp;</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
</footer>

blog/templates/blog/jumbotrom.html
 <div class="blog-header">
     <a href="/"><h1 class="blog-title">fullLove</h1></a>

     <p class="lead blog-description">Mr CJ</p>

      </div>

blog/templates/blog/nav.html
   <div class="nav-container">
		<nav class="nav">
			<header>
				<div class="logo">
					<a id="logo-value" href="/">CJ</a>
				</div>
			</header>
			<ul class="nav-links">
				<li><a href="">Home</a></li>
				<li><a href="">Code</a></li>
				<li><a href="">Videos</a></li>
				<li><a href="">About</a></li>
			</ul>
			<div class="burger">
				<div class="line1"></div>
				<div class="line2"></div>
				<div class="line3"></div>
			</div>
		</nav>
</div>

blog/templates/blog/nav_boot.html
 <div class="blog-masthead navbar-fixed-top">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="/">Home</a>
          <!--<a class="blog-nav-item" href="#">New features</a>-->
          <!--<a class="blog-nav-item" href="#">Press</a>-->
          <!--<a class="blog-nav-item" href="#">New hires</a>-->
          <!--<a class="blog-nav-item" href="#">About</a>-->
        </nav>
      </div>
    </div>

blog/templates/blog/paginator.html
<div class="pagination">
    <span class="step-links">

    </span>
</div>

{% if page_obj.has_other_pages %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

blog/templates/blog/pignator.html
<nav>
    {% if is_pignated %}
    <ul class="pager">
        {% if page_obj.has_previous %}
            <li><a href="#">Previous</a></li>
        {% endif %}
        {% if page_obj.has_next %}
            <li><a href="#">Next</a></li>
        {% endif %}
    </ul>
    {% endif %}
</nav>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  {% include 'blog/jumbotrom.html' %}
      <div class="row">

        <div class="col-sm-7 col-sm-offset-1 blog-main">

          <div class="blog-post">
            <h2 class="blog-post-title">{{ object.title }}</h2>
            <p class="blog-post-meta">{{ object.created }} by <a href="." id="author">{{ object.author }}</a></p>

            <p>{{ object.content|safe }}</p>
            <hr>

          </div><!-- /.blog-post -->


        </div><!-- /.blog-main -->

        {% include 'blog/sidebar.html' %}


      </div><!-- /.row -->

    </div><!-- /.container -->

    {% include 'blog/footer.html' %}

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block body %}
	 <div class="container">

     {% include 'blog/jumbotrom.html' %}

      <div class="row">

        <div class="col-sm-7 col-sm-offset-1 blog-main">
        {% for obj in object_list %}
          <div class="blog-post">
            <h3 class="blog-post-title">
				<a href="{% url 'blog:article_detail' obj.id obj.slug%}" id="title-post">{{ obj.title }}</a>
			</h3>
            <p class="blog-post-meta">
                {{ obj.created }}
                {% if obj.author %}
                    by <a href="." id="author">{{obj.author}}</a>
                {% endif %}
            </p>

	<p class="post-content"><!-- div for blog content -->
		{{ obj.content|truncatewords:105|safe }}
	</p><!--End of post-content div-->


          </div><!-- /.blog-post -->
            {% endfor %}


          {% include 'blog/paginator.html' %}

        </div><!-- /.blog-main -->

    {% include 'blog/sidebar.html' %}

      </div><!-- /.row -->

    </div><!-- /.container -->


{% include 'blog/footer.html' %}



{% endblock %}

blog/templates/blog/sidebar.html
    <div class="col-sm-4">
      <div class="col-sm-0"></div>

    <div class="col-sm-10 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Finding the <em>truth</em> is a delibrate call of action
            	I will not only ponder in my mind but find it and live through the rest of my life. Join me as we grow together.
            </p>
          </div>
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->
        <div class="col-sm-2"></div>
        </div><!-- sidebar container -->